### ISSUE TITLE
Gui not working on Linux Mint 17.3

### ISSUE THREAD

**Issue by f380cedric** [numixproject/numix-folders#143]
I tried with sudo. Here the output 

```shell
Traceback (most recent call last):
  File "/opt/numix-folders/gui/gui", line 220, in on_activate
    self.colourentries[i].set_max_width_chars(7)
AttributeError: 'Entry' object has no attribute 'set_max_width_chars'
```

**Comment by bil-elmoussaoui** [comment]
@f380cedric  really wired :o maybe something with the Gtk version, can you paste the output of `dpkg --get-selections | grep gtk`

**Comment by f380cedric** [comment]
```shell
gir1.2-gtk-3.0					install
gir1.2-gtkclutter-1.0				install
gir1.2-gtksource-3.0				install
gir1.2-javascriptcoregtk-3.0			install
gir1.2-nmgtk-1.0				install
gtk2-engines:amd64				install
gtk2-engines:i386				install
gtk2-engines-murrine:amd64			install
gtk2-engines-murrine:i386			install
gtk2-engines-oxygen:i386			install
gtk2-engines-pixbuf:amd64			install
gtk2-engines-pixbuf:i386			install
gtk3-engines-unico:amd64			install
ibus-gtk:i386					install
libcanberra-gtk-module:amd64			install
libcanberra-gtk-module:i386			install
libcanberra-gtk0:amd64				install
libcanberra-gtk0:i386				install
libcanberra-gtk3-0:amd64			install
libcanberra-gtk3-module:amd64			install
libclutter-gtk-1.0-0:amd64			install
libclutter-gtk-1.0-dbg:amd64			install
libdbusmenu-gtk3-4:amd64			install
libdbusmenu-gtk4:amd64				install
libgtk-3-0:amd64				install
libgtk-3-0-dbg:amd64				install
libgtk-3-bin					install
libgtk-3-common					install
libgtk-3-dev					install
libgtk-sharp-beans-cil				install
libgtk2-perl					install
libgtk2.0-0:amd64				install
libgtk2.0-0:i386				install
libgtk2.0-0-dbg					install
libgtk2.0-bin					install
libgtk2.0-cil					install
libgtk2.0-common				install
libgtkglext1					install
libgtkhtml-4.0-0				deinstall
libgtkhtml-editor-4.0-0				deinstall
libgtkmm-2.4-1c2a:amd64				install
libgtkmm-3.0-1:amd64				install
libgtksourceview-3.0-1:amd64			install
libgtksourceview-3.0-common			install
libgtksourceview2.0-0				install
libgtksourceview2.0-common			install
libgtkspell0					install
libjavascriptcoregtk-1.0-0:amd64		install
libjavascriptcoregtk-3.0-0:amd64		install
libnm-gtk-common				install
libnm-gtk0					install
libreoffice-gtk					install
libswt-cairo-gtk-3-jni				install
libswt-gtk-3-java				install
libswt-gtk-3-jni				install
libswt-webkit-gtk-3-jni				install
libwebkit2gtk-3.0-25:amd64			install
libwebkitgtk-1.0-0:amd64			install
libwebkitgtk-1.0-common				install
libwebkitgtk-3.0-0:amd64			install
libwebkitgtk-3.0-common				install
libwmf0.2-7-gtk					install
libwxgtk2.8-0:amd64				install
lightdm-gtk-greeter				install
mint-themes-gtk3				install
numix-gtk-theme					install
python-aptdaemon.gtk3widgets			install
python-gtk2					install
python-gtksourceview2				install
python3-aptdaemon.gtk3widgets			install
transmission-gtk				install
xdg-user-dirs-gtk				install
```

**Comment by bil-elmoussaoui** [comment]
Can you create an empty python file and put this code on it, execute the script using terminal (`python3`) and paste the output
```python
from gi.repository import Gtk
print(Gtk.get_major_version())
print(Gtk.get_minor_version())
```

**Comment by f380cedric** [comment]
```shell
3
10
```

**Comment by bil-elmoussaoui** [comment]
I don't know why this is happening.. and i can't test it right now. You can modify the file in '/opt/numix-folders/gui/gui` manually and remove this line `self.colourentries[i].set_max_width_chars(7)` everything should work fine but the gui will look a little bit out of place

**Comment by f380cedric** [comment]
It seems that set_max_width_chars was introduced with the 3.12 version of Gtk, I am on 3.10 ([there](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-max-width-chars))

**Comment by bil-elmoussaoui** [comment]
@wa4557 @dirtydancing What do you guys think about this? if we remove the `set_max_width_chars` the gui will look really ugly...
![screenshot from 2016-01-06 11-23-47](https://cloud.githubusercontent.com/assets/7660997/12140412/088d571e-b468-11e5-9e6f-7664466a0e97.png)
I still don't understand why some distros are still using a very old version of GTK... :(

**Comment by wa4557** [comment]
An if condition and if Gtk>=3.12 is used set the property?

**Comment by bil-elmoussaoui** [comment]
But still the gui will look ugly for old versions :P

**Comment by dirtydancing** [comment]
I can get back to this later. First thought: yeah, the GUI would look really ugly like that, after all the refining it has undergone. Second thought: Is this based on Ubuntu 14.04 LTS? Ubuntu 14.04 LTS should be supported if possible. Third thought: Maybe have two different GUI versions depending on the Gtk version? That way, all "modern" distros would profit, while the "old" ones would still be served.

**Comment by bil-elmoussaoui** [comment]
@dirtydancing i have no idea, but i think that ubuntu 14.04 uses gtk 3.12. I prefer creating two GUI versions, we use the old design for older version < 3.12 and we keep this new version for gtk >= 3.14. Let's see what @Foggalong think about this

**Comment by Foggalong** [comment]
I'd much sooner have an if condition than maintain multiple versions.

**Comment by f380cedric** [comment]
@bil-elmoussaoui  I think that Ubunutu 14.04 ) i still using gtk 3.10 ([source](http://packages.ubuntu.com/search?suite=trusty&arch=any&searchon=names&keywords=libgtk)

**Comment by dirtydancing** [comment]
@f380cedric Could you check if the pull request over at https://github.com/numixproject/numix-folders/pull/144 works for you, i.e. does your GUI look like the first one displayed over there? This is the relevant branch to test: https://github.com/bil-elmoussaoui/numix-folders/tree/patch-2

The GUI is working fine just as before with Arch/GNOME. This is Gtk 3.18, so it looks like the second screenshot over at https://github.com/numixproject/numix-folders/pull/144#issue-125162480.

**Comment by f380cedric** [comment]
@dirtydancing  from [there](https://github.com/bil-elmoussaoui/numix-folders/tree/patch-2), I have this
![Numix-Folders-Path-2](https://cloud.githubusercontent.com/assets/10184070/12149800/0098c398-b4a6-11e5-9c04-cac8c2f08cdc.png)

**Comment by dirtydancing** [comment]
Well, this looks OK imo, although a little different than in the other screenshot.

@bil-elmoussaoui Any idea why the title is `Numix Folders GUI` and not `Numix Folders` like in your screenshot for older Gtk versions?

**Comment by bil-elmoussaoui** [comment]
@dirtydancing i have no idea :p i didn't change the title, as you can see in the source code in my commit! @f380cedric Can you copy/paste the source of `gui` file in pastebin and paste the link here?

**Comment by f380cedric** [comment]
@bil-elmoussaoui  http://pastebin.com/pSVbPiM7

**Comment by bil-elmoussaoui** [comment]
I see, you've cloned the main repo that's why.. once you've cloned the repo you need to run `git pull origin patch-2`

**Comment by f380cedric** [comment]
Ha, I thought that copy url from path-2 was sufficient to clone this part of the repo -_- sorry :/
So, with the good branch (you have conflit between your master and patch 2) I have this 
![Numix Folders](https://cloud.githubusercontent.com/assets/10184070/12152318/36000a1a-b4b4-11e5-9b53-7e1469a991c1.png)

**Comment by bil-elmoussaoui** [comment]
@f380cedric not a problem :) i fixed a small issue, it should work fine now. Can you try again?

**Comment by f380cedric** [comment]
@bil-elmoussaoui  If I try to merge origin master (origin is [your repo](https://github.com/bil-elmoussaoui/numix-folders.git)) with origin patch-2, I have conflits 
![capture du 2016-01-06 20 50 48](https://cloud.githubusercontent.com/assets/10184070/12152883/38bf82c8-b4b7-11e5-8147-2092c90ac7b4.png)

**Comment by bil-elmoussaoui** [comment]
Looks fine for me :+1:

**Comment by dirtydancing** [comment]
Agreed :+1: 

And here is a screenshot with Arch/GNOME (Gtk 3.18), all fine here as well:

![numix-folders](https://cloud.githubusercontent.com/assets/7164227/12153987/3b8d6cd0-b4bd-11e5-9f75-da82762bedad.png)
